fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.1.6'
    hooks:
      - id: ruff
        exclude: ^(tests/|^tools/)
        args: [--fix, --exit-non-zero-on-fix]